# Generated by Django 3.2 on 2022-05-30 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalimage',
            name='image',
            field=models.ImageField(upload_to='2022-05-30 19:27:39.114004-4302', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='image',
            field=models.ImageField(blank=True, upload_to='2022-05-30 19:27:39.1128255696', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='tegs',
            field=models.ManyToManyField(related_name='tegs', to='news.TegsModel'),
        ),
    ]
