# Generated by Django 3.2 on 2022-05-30 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20220530_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsmodel',
            name='views_new',
            field=models.IntegerField(default=0, verbose_name='Просмотры'),
        ),
        migrations.AlterField(
            model_name='additionalimage',
            name='image',
            field=models.ImageField(upload_to='2022-05-30 20:32:27.2624396931', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='image',
            field=models.ImageField(blank=True, upload_to='2022-05-30 20:32:27.261111-9065', verbose_name='Image'),
        ),
    ]
