# Generated by Django 3.2 on 2022-05-31 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20220530_2032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tegsmodel',
            options={'verbose_name': 'Teg'},
        ),
        migrations.AlterField(
            model_name='additionalimage',
            name='image',
            field=models.ImageField(upload_to='2022-05-31 06:54:48.836633-5900', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='image',
            field=models.ImageField(blank=True, upload_to='2022-05-31 06:54:48.835316-6028', verbose_name='Image'),
        ),
    ]
